export const Quote: string[] = [
  "The LORD is my shepherd; I shall not want. (Psalm 23:1)",
  "Be still, and know that I am God. (Psalm 46:10)",
  "Come unto me, all ye that labour and are heavy laden, and I will give you rest. (Matthew 11:28)",
  "Peace I leave with you, my peace I give unto you. (John 14:27)",
  "Fear thou not; for I am with thee: be not dismayed; for I am thy God. (Isaiah 41:10)",
  "Now the God of hope fill you with all joy and peace in believing. (Romans 15:13)",
  "Casting all your care upon him; for he careth for you. (1 Peter 5:7)",
  "The LORD will give strength unto his people; the LORD will bless his people with peace. (Psalm 29:11)",
  "Now the Lord of peace himself give you peace always by all means. (2 Thessalonians 3:16)",
  "Yea, I have loved thee with an everlasting love. (Jeremiah 31:3)",
  "Nowhere with more quiet or freedom from trouble does a man retire than into his own soul. (Marcus Aurelius, Meditations)",
  "Men are disturbed, not by things, but by their views of things. (Epictetus, Enchiridion)",
  "Wherever there is a human being, there is an opportunity for kindness. (Seneca, On a Happy Life)",
  "Silence is a true friend who never betrays. (Confucius, Analects)",
  "Nature does not hurry, yet everything is accomplished. (Lao Tzu, Tao Te Ching)",
  "Better than a thousand hollow words is one word that brings peace. (Buddha, Dhammapada 100)",
  "This too shall pass. (Persian proverb)",
  "Behind the clouds is the sun still shining. (Longfellow, The Rainy Day)",
  "Nothing can bring you peace but yourself. (Emerson, Self-Reliance)",
  "Heaven is under our feet as well as over our heads. (Thoreau, Walden)",
  "Kindness is a language the deaf can hear and the blind can see. (Mark Twain)",
  "All shall be well, and all manner of thing shall be well. (Julian of Norwich, Revelations)",
  "Be happy for this moment. This moment is your life. (Omar Khayyam, Rubaiyat)",
  "Flow with whatever may happen, and let your mind be free. (Zhuangzi)",
  "Clouds come floating into my life to add color to my sunset sky. (Tagore, Stray Birds)",
  "Folks are usually about as happy as they decide to be. (Abraham Lincoln)",
  "Forever is composed of nows. (Emily Dickinson)",
  "Peace is always beautiful. (Walt Whitman, Leaves of Grass)",
  "Hatred is never appeased by hatred; it is appeased only by love. (Buddha, Dhammapada 5)",
  "Reflect upon your present blessings, not on your past misfortunes. (Charles Dickens, A Christmas Carol)"
];
